name: Unit Tests

on:
  pull_request

jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - uses: Pull all branches
        run: git pull

      - uses: c-hive/gha-yarn-cache@v1

      - name: Install dependencies
        run: yarn

      - name: Test affected code
        run: yarn affected:test

